services:
  webservice:
    image: mikez3/uniche-llm-webservice:latest  # Use Docker Hub image
    # image: uniche-llm-webservice:latest
    build:  # uncomment only when building locally
      context: .  # = Use the current folder (where this compose file is) as the base for everything.
    ports:
      - 8083:8000
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
